    $(document).ready(function(){
            $("h1").hide();
            $("#hide").click(function(){
                $("html").hide();
            })
        $("#show").click(function(){
            $("h1").show();
        });
    });
